version: '3'

services:
  nginx:
    image: nginx:mbaanni
    build: requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
#      adminer:
#        condition: service_started
    volumes:
      - wordpress:/var/www/html
      - phpmyadmin:/var/www/html/phpmyadmin
    ports:
      - 443:443
      - 80:80
    networks:
      - testo
    env_file:
      - .env
    restart: always

  wordpress:
    image: wordpress:mbaanni
    build: requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    networks:
      - testo
    env_file:
      - .env
    restart: always

  mariadb:
    image: mariadb:mbaanni
    build: requirements/mariadb
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - testo
    env_file:
      - .env
    restart: always
  my-php-admin:
    image: phpmyadmin:fpm-alpine
    container_name: phpmyadmin
    depends_on:
      - mariadb
    networks:
      - testo
    volumes:
      - phpmyadmin:/var/www/html
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/wordpress
      o: bind
    
  phpmyadmin:

  mariadb:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/mariadb
      o: bind

networks:
  testo:
    driver: bridge
